/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mconklin' at '1/15/17 4:34 PM' with Gradle 2.11
 *
 * @author mconklin, @date 1/15/17 4:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
